import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
import _main
import atestus as at

service = Service()
options = webdriver.ChromeOptions()
options.set_capability("goog:loggingPrefs", {"browser": "SEVERE"})
driver = webdriver.Chrome(service=service, options=options)
#driver = webdriver.Edge()
#driver = webdriver.Firefox()
driver.maximize_window()
wait = WebDriverWait(driver, 10)

#opening browser > entering npi and checking found provider

driver.get(at.Requests.devstage_pablo_weburl + "/for-providers/claim")
driver.implicitly_wait(3)
prov_claim_button = driver.find_element(By.XPATH, f'{at.ProvMainPage.prov_claim_button}')
wait.until(expected_conditions.visibility_of((prov_claim_button)))
prov_claim_button.click()
time.sleep(2)
npi_input = driver.find_element(By.XPATH, f'{at.ProvMainPage.npi_input}')
npi_input.send_keys(at.General.npi)
time.sleep(1)
print("Main page, prov NPI entered: --", npi_input.get_attribute("value"))
search_button = driver.find_element(By.XPATH, f'{at.ProvMainPage.search_button}')
search_button.click()
time.sleep(3)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/1_npi_found_provider.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/1_npi_found_provider.png')
yes_button = driver.find_element(By.XPATH, f'{at.ProvMainPage.yes_button}')
yes_button.click()
time.sleep(4)

#selection of services

try:
    add_serv_button = driver.find_element(By.XPATH, f'{at.ProvServicesPage.add_serv_button}')
    if add_serv_button.is_displayed:
        add_serv_button.click()
except:
    add_more_button = driver.find_element(By.XPATH, f'{at.ProvServicesPage.add_more_button}')
    if add_more_button.is_displayed:
        search_input = driver.find_element(By.XPATH, f'{at.ProvServicesPage.search_input}')
        search_input.send_keys(at.Methods.randomizer(at.General.diff_values))
        time.sleep(2)
        add_more_button.click()

time.sleep(2)
random_more_service1 = driver.find_element(By.XPATH, f'{at.Methods.randomizer(at.ProvServicesPage.more_services_list)}')
random_more_service2 = driver.find_element(By.XPATH, f'{at.Methods.randomizer(at.ProvServicesPage.more_services_list)}')
random_more_service3 = driver.find_element(By.XPATH, f'{at.Methods.randomizer(at.ProvServicesPage.more_services_list)}')
random_more_service4 = driver.find_element(By.XPATH, f'{at.Methods.randomizer(at.ProvServicesPage.more_services_list)}')
random_more_service5 = driver.find_element(By.XPATH, f'{at.Methods.randomizer(at.ProvServicesPage.more_services_list)}')
random_more_service6 = driver.find_element(By.XPATH, f'{at.Methods.randomizer(at.ProvServicesPage.more_services_list)}')
random_more_service7 = driver.find_element(By.XPATH, f'{at.Methods.randomizer(at.ProvServicesPage.more_services_list)}')
random_more_service8 = driver.find_element(By.XPATH, f'{at.Methods.randomizer(at.ProvServicesPage.more_services_list)}')
random_more_service9 = driver.find_element(By.XPATH, f'{at.Methods.randomizer(at.ProvServicesPage.more_services_list)}')
random_more_service1.click()
random_more_service2.click()
random_more_service3.click()
random_more_service4.click()
random_more_service5.click()
random_more_service6.click()
random_more_service7.click()
random_more_service8.click()
random_more_service9.click()
time.sleep(2)
cancel_button = driver.find_element(By.XPATH, f'{at.ProvServicesPage.cancel_button}')
cancel_button.click()
time.sleep(1)
search_input = driver.find_element(By.XPATH, f'{at.ProvServicesPage.search_input}')
search_input.send_keys(Keys.CONTROL, "a")
search_input.send_keys(Keys.DELETE)
time.sleep(1)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/2_saved_services.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/2_saved_services.png')
continue_button1 = driver.find_element(By.XPATH, f'{at.ProvServicesPage.continue_button1}')
continue_button1.click()
time.sleep(4)

#selection of locations and insurances

location1_button = driver.find_element(By.XPATH, f'{at.LocInsurPages.location1_button}')
location1_button.click()
time.sleep(2)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/3_selected_locations.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/3_selected_locations.png')
continue_button2 = driver.find_element(By.XPATH, f'{at.LocInsurPages.continue_button2}')
continue_button2.click()
time.sleep(4)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/4_list_of_insurances.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/4_list_of_insurances.png')
skip_button = driver.find_element(By.XPATH, f'{at.LocInsurPages.skip_button}')
skip_button.click()
time.sleep(2)

#filling the contact information form and setting preferred method

contact_email_input = driver.find_element(By.XPATH, f'{at.LocInsurPages.contact_email_input}')
contact_phone_input = driver.find_element(By.XPATH, f'{at.LocInsurPages.contact_phone_input}')
contact_fax_input = driver.find_element(By.XPATH, f'{at.LocInsurPages.contact_fax_input}')
contact_email_input.send_keys(at.General.unique_email)
contact_phone_input.send_keys(at.Methods.randomizer(at.General.usPhoneNums))
contact_fax_input.send_keys(at.Methods.randomizer(at.General.usPhoneNums))
time.sleep(2)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/5_contact_information.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/5_contact_information.png')
print("Contact info form, contact email entered: --", contact_email_input.get_attribute("value"))
print("Contact info form, contact phone entered: --", contact_phone_input.get_attribute("value"))
print("Contact info form, contact fax entered: --", contact_fax_input.get_attribute("value"))
continue_button3 = driver.find_element(By.XPATH, f'{at.LocInsurPages.continue_button3}')
continue_button3.click()
time.sleep(2)
pref_email_box = driver.find_element(By.XPATH, f'{at.LocInsurPages.pref_email_box}')
pref_fax_box = driver.find_element(By.XPATH, f'{at.LocInsurPages.pref_fax_box}')
pref_email_box.click()
pref_fax_box.click()
continue_button4 = driver.find_element(By.XPATH, f'{at.LocInsurPages.continue_button4}')
continue_button4.click()
time.sleep(3)
continue_button5 = driver.find_element(By.XPATH, f'{at.LocInsurPages.continue_button5}')
continue_button5.click()
time.sleep(2)

#verify flow now finished, profile verified > Provider / PA account creation starts

create_prov_button = driver.find_element(By.XPATH, f'{at.VerifyIdentityPage.create_prov_button}')
create_prov_button.click()
time.sleep(2)
prov_med_license_input = driver.find_element(By.XPATH, f'{at.VerifyIdentityPage.prov_med_license_input}')
prov_state_license_dropdown = driver.find_element(By.CSS_SELECTOR, f'{at.VerifyIdentityPage.prov_state_license_dropdown}')
prov_dob_input = driver.find_element(By.XPATH, f'{at.VerifyIdentityPage.prov_dob_input}')
prov_med_license_input.send_keys(at.Methods.randomizer(at.General.diff_values))
prov_state_license_dropdown.send_keys(at.Methods.randomizer(at.General.usStates))
prov_state_license_dropdown.send_keys(Keys.DOWN)
prov_state_license_dropdown.send_keys(Keys.ENTER)
#driver.execute_script("arguments[0].setAttribute('value', 'California')", state_license_dropdown)
prov_dob_input.send_keys(at.Methods.randomizer(at.General.datesOfBirth))
time.sleep(2)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/6_verify_identity_info.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/6_verify_identity_info.png')
print("Verify Identity, med license entered: --", prov_med_license_input.get_attribute("value"))
print("Verify Identity, state of license selected: --", prov_state_license_dropdown.get_attribute("value"))
print("Verify Identity, DOB entered: --", prov_dob_input.get_attribute("value"))
next_button1 = driver.find_element(By.XPATH, f'{at.VerifyIdentityPage.next_button1}')
next_button1.click()
time.sleep(2)

#filling info for the practice

prac_input = driver.find_element(By.XPATH, f'{at.WorkInfoPage.prac_input}')
prac_input.send_keys(at.Methods.randomizer(at.General.practiceNames))
time.sleep(2)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/7_practice_info.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/7_practice_info.png')
print("Work Info, prac name entered: --", prac_input.get_attribute("value"))
next_button2 = driver.find_element(By.XPATH, f'{at.WorkInfoPage.next_button2}')
next_button2.click()
time.sleep(3)

#creating a password for the account

prov_password_input = driver.find_element(By.XPATH, f'{at.CreatePasswordPage.prov_password_input}')
prov_password_confirm = driver.find_element(By.XPATH, f'{at.CreatePasswordPage.prov_password_confirm}')
prov_password_input.send_keys("Qwerty123!")
prov_password_confirm.send_keys("Qwerty123!")
time.sleep(1)
next_button3 = driver.find_element(By.XPATH, f'{at.CreatePasswordPage.next_button3}')
next_button3.click()
time.sleep(2)
# print browser console messages (not working for Firefox)
for entry in driver.get_log('browser'):
    print(entry)
verify_code_input = driver.find_element(By.XPATH, f'{at.CreatePasswordPage.verify_code_input}')
verify_code_input.send_keys("010101")
time.sleep(2)
login_button = driver.find_element(By.XPATH, f'{at.WorkInfoPage.login_button}')
login_button.click()
time.sleep(5)
# print browser console messages (not working for Firefox)
for entry in driver.get_log('browser'):
    print(entry)

#checking all created entities and info correctness on the web side

accept_button = driver.find_element(By.XPATH, f'{at.WebProvPages.accept_button}')
accept_button.click()
time.sleep(8)
x_button = driver.find_element(By.XPATH, f'{at.WebProvPages.x_button}')
x_button.click()
time.sleep(3)
prac_loc_selector = driver.find_element(By.XPATH, f'{at.WebProvPages.prac_loc_selector}')
prac_loc_selector.click()
time.sleep(3)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/8_created_prac_locs.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/8_created_prac_locs.png')
time.sleep(3)
profile_selector = driver.find_element(By.XPATH, f'{at.WebProvPages.profile_selector}')
profile_selector.click()
time.sleep(3)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/9_created_provider_profile.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/9_created_provider_profile.png')
insurance_tab = driver.find_element(By.XPATH, f'{at.WebProvPages.insurance_tab}')
locations_tab = driver.find_element(By.XPATH, f'{at.WebProvPages.locations_tab}')
insurance_tab.click()
time.sleep(3)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/10_created_insurances.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/10_created_insurances.png')
locations_tab.click()
time.sleep(5)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/11_created_locations.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/11_created_locations.png')
location1_open_tick = driver.find_element(By.XPATH, f'{at.WebProvPages.location1_open_tick}')
location1_open_tick.click()
time.sleep(1)
loc1_serv_selector = driver.find_element(By.XPATH, f'{at.WebProvPages.loc1_serv_selector}')
loc1_serv_selector.click()
time.sleep(3)
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider1}/12_created_services.png')
driver.save_screenshot(f'{at.Paths.screenpath_claimProvider2}/12_created_services.png')
# print browser console messages (not working for Firefox)
for entry in driver.get_log('browser'):
    print(entry)
driver.quit()